class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'uz': {
      'app_title': 'AutoPrime LMS — O\'quvchi Kabineti',
      'login_title': 'Tizimga Kirish',
      'login_subtitle': 'AutoPrime avtomaktabi o\'quvchilari uchun maxsus dastur',
      'enter_phone': 'Telefon raqamingizni kiriting:',
      'phone_placeholder': '+998 90 123 45 67',
      'send_otp_btn': 'Kodni Olish',
      'enter_otp_title': 'Telegram Tasdiqlash Kodi',
      'enter_otp_subtitle': '@LmsAutoprimeBot botiga yuborilgan 6 xonali kodni kiriting:',
      'verify_btn': 'Tasdiqlash va Kirish',
      'resend_otp': 'Kodni qayta yuborish',
      'tab_overview': 'Bosh Sahifa',
      'tab_tickets': '130 ta Biletlar',
      'tab_lms': 'Video Darslar & PDF',
      'tab_drivings': 'Amaliy Mashg\'ulotlar',
      'tab_signs': 'Yo\'l Belgilari',
      'start_mock_exam': 'Ichki Nazorat Imtihoni',
      'mock_exam_desc': '20 ta savol • 25 daqiqa • Kamida 18 ta to\'g\'ri javob (90%)',
      'question': 'Savol',
      'explanation': 'Tavsif',
      'font_size': 'Shrift',
      'finish_test': 'Testni Yakunlash',
      'next_question': 'Keyingi',
      'prev_question': 'Oldingi',
      'correct_answer': 'To\'g\'ri javob!',
      'wrong_answer': 'Noto\'g\'ri javob!',
      'update_available_title': 'Yangi Versiya Mavjud!',
      'update_now_btn': 'Hozir Yangilash',
      'check_updates': 'Dasturni Yangilash',
      'checking_updates': 'Yangilanishlar tekshirilmoqda...',
      'latest_version': 'Sizda eng so\'nggi versiya o\'rnatilgan',
      'update_error': 'Yangilanishlarni tekshirishda xatolik yuz berdi',
      'session_terminated_title': 'Sessiya To\'xtatildi',
      'logout': 'Chiqish',
    },
    'ru': {
      'app_title': 'AutoPrime LMS — Кабинет Ученика',
      'login_title': 'Вход в систему',
      'login_subtitle': 'Специальное приложение для учеников автошколы AutoPrime',
      'enter_phone': 'Введите ваш номер телефона:',
      'phone_placeholder': '+998 90 123 45 67',
      'send_otp_btn': 'Получить код',
      'enter_otp_title': 'Код подтверждения Telegram',
      'enter_otp_subtitle': 'Введите 6-значный код, отправленный боту @LmsAutoprimeBot:',
      'verify_btn': 'Подтвердить и войти',
      'resend_otp': 'Отправить код повторно',
      'tab_overview': 'Главная',
      'tab_tickets': '130 Билетов',
      'tab_lms': 'Видеоуроки & PDF',
      'tab_drivings': 'Вождение',
      'tab_signs': 'Дорожные Знаки',
      'start_mock_exam': 'Внутренний Экзамен',
      'mock_exam_desc': '20 вопросов • 25 минут • Минимум 18 верных ответов (90%)',
      'question': 'Вопрос',
      'explanation': 'Пояснение',
      'font_size': 'Шрифт',
      'finish_test': 'Завершить тест',
      'next_question': 'Далее',
      'prev_question': 'Назад',
      'correct_answer': 'Правильный ответ!',
      'wrong_answer': 'Неправильный ответ!',
      'update_available_title': 'Доступно обновление!',
      'update_now_btn': 'Обновить сейчас',
      'check_updates': 'Обновить программу',
      'checking_updates': 'Проверка обновлений...',
      'latest_version': 'У вас установлена последняя версия',
      'update_error': 'Ошибка при проверке обновлений',
      'session_terminated_title': 'Сессия завершена',
      'logout': 'Выйти',
    },
    'krill': {
      'app_title': 'AutoPrime LMS — Ўқувчи Кабинети',
      'login_title': 'Тизимга Кириш',
      'login_subtitle': 'AutoPrime автомактаби ўқувчилари учун махсус дастур',
      'enter_phone': 'Телефон рақамингизни киритинг:',
      'phone_placeholder': '+998 90 123 45 67',
      'send_otp_btn': 'Кодни Олиш',
      'enter_otp_title': 'Telegram Тасдиқлаш Коди',
      'enter_otp_subtitle': '@LmsAutoprimeBot ботига юборилган 6 хонали кодни киритинг:',
      'verify_btn': 'Тасдиқлаш ва Кириш',
      'resend_otp': 'Кодни қайта юбориш',
      'tab_overview': 'Бош Саҳифа',
      'tab_tickets': '130 та Билетлар',
      'tab_lms': 'Видео Дарслар & PDF',
      'tab_drivings': 'Амалий Машғулотлар',
      'tab_signs': 'Йўл Белгилари',
      'start_mock_exam': 'Ички Назорат Имтиҳони',
      'mock_exam_desc': '20 та савол • 25 дақиқа • Камида 18 та тўғри жавоб (90%)',
      'question': 'Савол',
      'explanation': 'Тавсиф',
      'font_size': 'Шрифт',
      'finish_test': 'Тестни Якунлаш',
      'next_question': 'Кейинги',
      'prev_question': 'Олдинги',
      'correct_answer': 'Тўғри жавоб!',
      'wrong_answer': 'Нотўғри жавоб!',
      'update_available_title': 'Янги Версия Мавжуд!',
      'update_now_btn': 'Ҳозир Янгилаш',
      'check_updates': 'Дастурни Янгилаш',
      'checking_updates': 'Янгиланишлар текширилмоқда...',
      'latest_version': 'Сизда энг сўнгги версия ўрнатилган',
      'update_error': 'Янгиланишларни текширишда хатолик юз берди',
      'session_terminated_title': 'Сессия Тўхтатилди',
      'logout': 'Чиқиш',
    },
    'en': {
      'app_title': 'AutoPrime LMS — Student Portal',
      'login_title': 'Sign In',
      'login_subtitle': 'Official application for AutoPrime driving school students',
      'enter_phone': 'Enter your phone number:',
      'phone_placeholder': '+998 90 123 45 67',
      'send_otp_btn': 'Get Code',
      'enter_otp_title': 'Telegram Verification Code',
      'enter_otp_subtitle': 'Enter the 6-digit code sent to @LmsAutoprimeBot:',
      'verify_btn': 'Verify & Sign In',
      'resend_otp': 'Resend code',
      'tab_overview': 'Dashboard',
      'tab_tickets': '130 Tickets',
      'tab_lms': 'Video Lessons & PDF',
      'tab_drivings': 'Driving Lessons',
      'tab_signs': 'Road Signs',
      'start_mock_exam': 'Internal Mock Exam',
      'mock_exam_desc': '20 questions • 25 minutes • At least 18 correct answers (90%)',
      'question': 'Question',
      'explanation': 'Explanation',
      'font_size': 'Font Size',
      'finish_test': 'Finish Quiz',
      'next_question': 'Next',
      'prev_question': 'Previous',
      'correct_answer': 'Correct Answer!',
      'wrong_answer': 'Wrong Answer!',
      'update_available_title': 'New Update Available!',
      'update_now_btn': 'Update Now',
      'check_updates': 'Check for Updates',
      'checking_updates': 'Checking for updates...',
      'latest_version': 'You have the latest version installed',
      'update_error': 'Error checking for updates',
      'session_terminated_title': 'Session Terminated',
      'logout': 'Sign Out',
    },
  };

  static String tr(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['uz']?[key] ?? key;
  }
}
